# Changing content of this file requires a server restart
# in order to be considered.


# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


gmail_domain: gmail.com
gmail_username: user@gmail.com
gmail_password: _a_pass_
allow_signup: true
# or else uncomment the following:
# delivery_method: test


slack_invite_url: ''
SLACK_API_TOKEN: ''

RECAPTCHA_SITE_KEY: ''
RECAPTCHA_SECRET_KEY: ''

default_url_options_host: localhost
default_url_options_port: "3000"

development:
  default_url_options_host: localhost
  default_url_options_port: "3000"
  section_activity_feed: "true"
  section_projects: "false"
  section_missions: "true"
  section_user_messages: "true"
  RECAPTCHA_SITE_KEY: 6LeoC8QUAAAAAC9QHj_opxHlFvkMPLyUjIfvgOyt
  RECAPTCHA_SECRET_KEY: 6LeoC8QUAAAAAOrIf4M5Go9buM1M-trBP17d2BKS

beta:
  default_url_options_host: beta.collabmachine.com
  default_url_options_port: "80"
  section_activity_feed: "true"
  section_projects: "true"
  section_missions: "true"
  section_user_messages: "true"

production:
  default_url_options_host: collabmachine.com
  default_url_options_port: "80"
  section_activity_feed: "false"
  section_projects: "false"
  section_missions: "false"
  section_user_messages: "false"
